### PR TITLE
use equals() and fix onBuildTriggered()

### PR DESCRIPTION
**Pull request by jlebon**
We weren't checking for the "--none--" magic string in
onBuildTriggered(), which caused the the commit status updating to fail.
Also use String.equals() to check the actual content of the string.

### CODE REVIEW

**Comment by jlebon** [comment]
Added another commit that adds support for disabling certain commit status updates.

**Comment by jlebon** [comment]
@DavidTanner Could you review these commits? The first one I think is required in order for the defaults fix to work. The second would be a nice-to-have.

**Comment by DavidTanner** [comment]
Would you please open this against jenkinsci/master?  I didn't notice it till after I had merged things.  Thanks.  I will merge it tomorrow, and then cut a release.

**Comment by jlebon** [comment]
Done! :)
https://github.com/jenkinsci/ghprb-plugin/pull/182

**Comment by DavidTanner** [comment]
Thanks!

**Pull request closed without merging**
